### ISSUE TITLE
[ISSUE] Rapid Updation of Participant.js is leading to merge conflicts

### ISSUE THREAD

**Issue by iamAyushChamoli** [iamAyushChamoli/hacktoberfest-24#86]
## Description
As per the current functionality of the site, after one of the contributors updates their details in the participants.js and other related files, a merge conflict is induced in the PRs submitted by other contributors. Because of which the other participants are required to submit a fresh commit by syncing the fork one participant at a time. 

This is an inefficient approach and we would like a revamp of this system. If you have suggestions for an alternate method of updating the participants.js data without inducing a merge conflict upon every commit, please share the details and we'll assign it to you after a brief discussion.

- **Is this a bug or a feature request?**: (Enhancement)
- **What is the current behavior?**: updation of participants.js file induces a merge conflict everytime a new participant is added.
- **What is the expected behavior?**: No merge conflict.

**Comment by RishaubKumar** [comment]
I am attempting it kindly assign it to me under hacktoberfest label

**Comment by iamAyushChamoli** [comment]
@RishaubKumar please read the description carefully, it clearly mentions that you need to explain the changes that you are proposing. 
Also, please don't spam comments under every issue to be assigned under the hacktoberfest label. You can work on one issue at a time.

That being said, if you have a solution, please share it here in the comments so that everyone can discuss it.

**Comment by RishaubKumar** [comment]
@iamAyushChamoli 
here is my proposed solution
Instead of all participants editing the same participants.js file, we can modify the system to have one file per participant. Each participant would add their information to a unique file (e.g., participants/<username>.json or .js). This reduces the chance of conflicts because participants are working on separate files.
Steps to Implement:
Refactor the code to load all participant files dynamically from the participants folder.
Each contributor adds a file named after their username (e.g., participants/sanjeev.js).
This decentralizes the process and makes it easier for contributors to add their information without stepping on each other's toes.

**Comment by iamAyushChamoli** [comment]
@RishaubKumar You can start working on implementing this solution and create a PR with it. If the solution is working and it does not break the prod, we will assign the issue to you before we merge the PR. 
I need to keep this issue open ended in the meantime so that other contributors can also suggest some changes that might be more efficient.

**Comment by iamAyushChamoli** [comment]
@RishaubKumar Also, please remember to complete the issue you are working on already before you start working on another issue.

**Comment by RishaubKumar** [comment]
@iamAyushChamoli sure

**Comment by RishaubKumar** [comment]
@iamAyushChamoli I have implemented the solution please merge my old pull request and assign this to me under hacktoberfest label so I can create pull request
